<?php

class JConfig {
	var $offline = '0';
	var $editor = 'tinymce';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '0';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'Nfk71OzLuZI0G3Av';
	var $gzip = '0';
	var $error_reporting = '1';
	var $xmlrpc_server = '0';
	var $log_path = '/www/sistersoul/htdocs/joomla/logs';
	var $tmp_path = '/www/sistersoul/htdocs/joomla/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '21';
	var $ftp_user = '';
	var $ftp_pass = '';
	var $ftp_root = '';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'cultivarte';
	var $db = 'sister';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'info@sistersoul.com.ar';
	var $fromname = 'Sister Soul';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'ssl';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = '';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '15';
	var $session_handler = 'database';
	var $password = 'cultivarte2016';
	var $sitename = 'Sister Soul';
	var $MetaDesc = 'Joomla! - el motor de portales dinámicos y sistema de administración de contenidos';
	var $MetaKeys = 'joomla, Joomla';
	var $offline_message = 'El sitio está desactivado por tareas de mantenimiento  Por favor, vuelva más tarde.';
}
?>
